export const REGIONS = [
  'North America - East',
  'North America - West',
  'EMEA',
  'APAC',
  'India',
];

export const AI_BD_OPTIONS = ['All', 'AI', 'BD'];

export const GEO_TERR_OPTIONS = ['All', 'Enterprise', 'Commercial', 'SMB'];

export const SALES_MANAGERS = {
  'North America - East': [
    'Michael Thornton',
    'Sarah Kimura',
    'David Osei',
    'Laura Petersen',
    'James Whitfield',
    'Amanda Russo',
  ],
  'North America - West': [
    'Carlos Delgado',
    'Priya Nair',
    'Kevin Brandt',
    'Tiffany Cho',
    'Nathan Abrams',
    'Rachel Fontaine',
  ],
  EMEA: [
    'Alistair Hughes',
    'Marie-Claire Dubois',
    'Stefan Braun',
    'Fatima Al-Rashid',
    'Luca Ferretti',
    'Ingrid Svensson',
    'Kofi Mensah',
  ],
  APAC: [
    'Yuki Nakamura',
    'Lin Wei',
    'Arjun Sharma',
    'Soo-Jin Park',
    'Budi Santoso',
    'Mei Ling Ho',
  ],
  India: [
    'Rohan Verma',
    'Anjali Mehta',
    'Sanjay Pillai',
    'Pooja Iyer',
    'Vivek Bhatia',
    'Nisha Kapoor',
  ],
};

export const MOCK_AE_DATA = [
  {
    id: 'ae-001',
    aeName: 'Jordan Blake',
    role: 'AE II – Enterprise GTS',
    cv: 2400,
    targetBookingSize: 2800,
    availableCapacity: 1,
    pctTargetFromSizeAchieved: 55,
    proxyBuReview: 78,
    proxyBuReview2: 81,
    proxySizeDiscount: 72,
    proxyGraded: 76,
    region: 'North America - East',
    aibd: 'AI',
    geoTerr: 'Enterprise',
    manager: 'Michael Thornton',
  },
  {
    id: 'ae-002',
    aeName: 'Morgan Castillo',
    role: 'AE III – Commercial GBS',
    cv: 1850,
    targetBookingSize: 2000,
    availableCapacity: 2,
    pctTargetFromSizeAchieved: 68,
    proxyBuReview: 65,
    proxyBuReview2: 70,
    proxySizeDiscount: 60,
    proxyGraded: 65,
    region: 'North America - East',
    aibd: 'BD',
    geoTerr: 'Commercial',
    manager: 'Michael Thornton',
  },
  {
    id: 'ae-003',
    aeName: 'Avery Chen',
    role: 'AE I – SMB GTS',
    cv: 950,
    targetBookingSize: 1100,
    availableCapacity: 0,
    pctTargetFromSizeAchieved: 86,
    proxyBuReview: 55,
    proxyBuReview2: 58,
    proxySizeDiscount: 50,
    proxyGraded: 54,
    region: 'North America - East',
    aibd: 'AI',
    geoTerr: 'SMB',
    manager: 'Michael Thornton',
  },
  {
    id: 'ae-004',
    aeName: 'Taylor Singh',
    role: 'AE II – Enterprise GBS',
    cv: 3200,
    targetBookingSize: 3500,
    availableCapacity: 3,
    pctTargetFromSizeAchieved: 72,
    proxyBuReview: 88,
    proxyBuReview2: 91,
    proxySizeDiscount: 85,
    proxyGraded: 88,
    region: 'North America - East',
    aibd: 'BD',
    geoTerr: 'Enterprise',
    manager: 'Sarah Kimura',
  },
  {
    id: 'ae-005',
    aeName: 'Riley Okafor',
    role: 'AE III – Commercial GTS',
    cv: 1100,
    targetBookingSize: 1300,
    availableCapacity: 1,
    pctTargetFromSizeAchieved: 58,
    proxyBuReview: 70,
    proxyBuReview2: 74,
    proxySizeDiscount: 68,
    proxyGraded: 71,
    region: 'North America - East',
    aibd: 'AI',
    geoTerr: 'Commercial',
    manager: 'Sarah Kimura',
  },
  {
    id: 'ae-006',
    aeName: 'Casey Navarro',
    role: 'AE II – Enterprise GTS',
    cv: 2750,
    targetBookingSize: 3000,
    availableCapacity: 0,
    pctTargetFromSizeAchieved: 91,
    proxyBuReview: 60,
    proxyBuReview2: 63,
    proxySizeDiscount: 55,
    proxyGraded: 59,
    region: 'North America - East',
    aibd: 'BD',
    geoTerr: 'Enterprise',
    manager: 'David Osei',
  },
  {
    id: 'ae-007',
    aeName: 'Quinn Patel',
    role: 'AE I – SMB GBS',
    cv: 680,
    targetBookingSize: 900,
    availableCapacity: 4,
    pctTargetFromSizeAchieved: 45,
    proxyBuReview: 82,
    proxyBuReview2: 79,
    proxySizeDiscount: 77,
    proxyGraded: 80,
    region: 'North America - East',
    aibd: 'AI',
    geoTerr: 'SMB',
    manager: 'David Osei',
  },
];

export const REBALANCE_ACCOUNTS = [
  {
    id: 'acc-001',
    aeName: 'Jordan Blake',
    company: 'Nexgen Systems Inc.',
    cv: 420000,
    sinceDate: '2021-03',
    country: 'USA',
    state: 'New York',
    industry: 'Technology',
    segment: 'Enterprise',
    sizeM: 1.2,
    proxyPremiumNotes:
      'High renewal probability. Expansion opportunity in Q3. Premium account flagged for upsell.',
    history: [
      { year: 2022, cv: 310000, notes: 'Initial contract' },
      { year: 2023, cv: 370000, notes: 'Expanded seat count' },
      { year: 2024, cv: 420000, notes: 'Multi-product adoption' },
    ],
  },
  {
    id: 'acc-002',
    aeName: 'Taylor Singh',
    company: 'Arcturus Financial Group',
    cv: 780000,
    sinceDate: '2019-07',
    country: 'USA',
    state: 'Illinois',
    industry: 'Financial Services',
    segment: 'Large Enterprise',
    sizeM: 3.4,
    proxyPremiumNotes:
      'Strategic account. BU review pending. Discount applied for multi-year deal.',
    history: [
      { year: 2021, cv: 550000, notes: 'Global expansion' },
      { year: 2022, cv: 650000, notes: 'Premium tier upgrade' },
      { year: 2023, cv: 780000, notes: 'New LOB added' },
    ],
  },
  {
    id: 'acc-003',
    aeName: 'Quinn Patel',
    company: 'Luminary Health Partners',
    cv: 195000,
    sinceDate: '2022-11',
    country: 'Canada',
    state: 'Ontario',
    industry: 'Healthcare',
    segment: 'Commercial',
    sizeM: 0.8,
    proxyPremiumNotes: 'Growth trajectory strong. Recommend territory move to capitalize.',
    history: [
      { year: 2023, cv: 140000, notes: 'Pilot program' },
      { year: 2024, cv: 195000, notes: 'Full deployment' },
    ],
  },
  {
    id: 'acc-004',
    aeName: 'Riley Okafor',
    company: 'Vantage Retail Solutions',
    cv: 310000,
    sinceDate: '2020-04',
    country: 'USA',
    state: 'Texas',
    industry: 'Retail',
    segment: 'Enterprise',
    sizeM: 1.5,
    proxyPremiumNotes:
      'At-risk renewal. Competitor activity noted. Requires executive sponsorship.',
    history: [
      { year: 2021, cv: 280000, notes: 'Initial onboarding' },
      { year: 2022, cv: 295000, notes: 'Stable renewal' },
      { year: 2023, cv: 310000, notes: 'Minor expansion' },
    ],
  },
  {
    id: 'acc-005',
    aeName: 'Morgan Castillo',
    company: 'Pinnacle Manufacturing Co.',
    cv: 540000,
    sinceDate: '2018-09',
    country: 'USA',
    state: 'Michigan',
    industry: 'Manufacturing',
    segment: 'Large Enterprise',
    sizeM: 2.1,
    proxyPremiumNotes: 'Long-standing account. Proxy score high. Collapse candidate if AE overloaded.',
    history: [
      { year: 2020, cv: 410000, notes: 'Pre-COVID baseline' },
      { year: 2021, cv: 460000, notes: 'Recovery growth' },
      { year: 2022, cv: 510000, notes: 'Digital transformation' },
      { year: 2023, cv: 540000, notes: 'Stable renewal' },
    ],
  },
];
